name: translate

on:
  workflow_dispatch:
    inputs:
      source:
        description: 'Source files'
        required: True
        default: "data/{spells,class}/*.json data/*.json data/book/*.json data/bestiary/*.json data/adventure/*.json"

jobs:
  translate:
    strategy:
      max-parallel: 1
      matrix:
        language: [ 'es', 'de', 'it', 'ru', 'zh' ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        ref: 'translations'
    - uses: actions/setup-python@v3
      with:
        python-version: '3.9'
        architecture: 'x64'
    - name: Set up dependencies
      run: |
           sudo apt-get install -y firefox
           pip3 install selenium webdriver_manager
    - name: Generate translations
      continue-on-error: true
      run: |
           cd $GITHUB_WORKSPACE
           ./translation/translate.py --language ${{ matrix.language }} --maxrun 9000 --translate --deepl ${{ github.event.inputs.source }}
           npm run gen-all
    - name: Save results
      continue-on-error: true
      run: |
           git config user.name "Automatic translator"
           git config user.email "<>"
           git add data.${{ matrix.language }}/ translation/cache/${{ matrix.language }}/
           git commit -m 'automatic translation'
           git pull --rebase
           git push origin translations
  deploy:
    needs: translate
    runs-on: ubuntu-latest
    steps:
       - uses: actions/checkout@master
         with:
           ref: 'translations'
           fetch-depth: 0 # So we get the last official release tag

       - name: cache buster
         run: |
              cd $GITHUB_WORKSPACE
              VERSION=$(git describe --tags --abbrev=0)
              bash ./.github/add-query-strings.sh "${VERSION}.$(date +%s)"

       # See: https://github.com/JamesIves/github-pages-deploy-action
       - name: Deploy
         uses: JamesIves/github-pages-deploy-action@releases/v4
         with:
           branch: gh-pages-translated
           folder: .
